-- 코드를 입력하세요
SELECT AIS.ANIMAL_ID, AIS.ANIMAL_TYPE, AIS.NAME
FROM ANIMAL_INS AIS JOIN ANIMAL_OUTS AOS ON AIS.ANIMAL_ID = AOS.ANIMAL_ID
WHERE AIS.SEX_UPON_INTAKE LIKE "Intact%" 
AND (AOS.SEX_UPON_OUTCOME LIKE "Spayed%"
OR AOS.SEX_UPON_OUTCOME LIKE "Neutered%")
ORDER BY AIS.ANIMAL_ID
